# Generated by Django 2.2.5 on 2020-10-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=164, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_type', models.CharField(choices=[('Trousers', 'Trousers'), ('Shirt', 'Shirt'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory'), ('Hoodie/Sweater', 'Hoodie/Sweater'), ('Trackpants', 'Trackpants'), ('Tee', 'Tee')], max_length=164)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
